version: '3.1'

services:
  # api service
  anomaly_app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    ports:
        # host port:container port, defaults é 3000 assim como no main.ts
      - ${APP_PORT-5000}:80
    container_name: anomaly_app
    restart: always
    volumes:
      - .:/usr/project/anomaly_app
    environment:
      - APP_ENV_MODE=${APP_ENV_MODE}
    networks:
      - anomaly_network
      - app-anomaly

networks:
  anomaly_network:
    driver: bridge
  app-anomaly:
    external: true
      